version: '3.8'
services:
  front:
    container_name: front
    image: front
    ports:
      - 3000:3000
    build: 
      context: .
      dockerfile: Dockerfile2
      target: development
    working_dir: /front
  
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /api
    ports:
      - 9090:9090
  
  
  
  phpmyadmin_accounts:
    image: phpmyadmin
    ports:
      - 7071:80
    environment:
      - PMA_ARBITRARY=0
    depends_on:
      - database
    links:
      - database:db

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db:



